version: '3'

services:
  books_db:
    image: postgres
    env_file:
      - ./.env

  books_api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "9000:8000"
    depends_on:
      - books_db
    env_file:
      - ./.env
